const properties = [
    {
      id: 1,
      title: "Luxury Villa in LA",
      price: "$1,250,000",
      image: "/images/villa.jpg", // Replace with actual image path
      location: "Los Angeles, CA",
      bedrooms: 4,
      bathrooms: 3,
      sqft: 7000,
    },
    {
      id: 2,
      title: "Modern Apartment in NYC",
      price: "$850,000",
      image: "/images/apartment.jpg",
      location: "New York, NY",
      bedrooms: 3,
      bathrooms: 2,
      sqft: 1800,
    },
    {
      id: 3,
      title: "Beachfront House in Miami",
      price: "$2,100,000",
      image: "/images/beachfront.jpg",
      location: "Miami, FL",
      bedrooms: 5,
      bathrooms: 4,
      sqft: 5000,
    },
    {
      id: 4,
      title: "Cozy Cottage in Denver",
      price: "$450,000",
      image: "/images/cottage.jpg",
      location: "Denver, CO",
      bedrooms: 2,
      bathrooms: 1,
      sqft: 1200,
    },
    {
      id: 5,
      title: "Penthouse in San Francisco",
      price: "$3,500,000",
      image: "/images/penthouse.jpg",
      location: "San Francisco, CA",
      bedrooms: 4,
      bathrooms: 3,
      sqft: 3500,
    },
    {
      id: 6,
      title: "Suburban Home in Texas",
      price: "$650,000",
      image: "/images/suburban.jpg",
      location: "Austin, TX",
      bedrooms: 3,
      bathrooms: 2,
      sqft: 2500,
    },
  ];
  
  export default properties;
  